sudo: false
language: python

addons:
  postgresql: "9.6"

branches:
  only:
  - master


matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.8
      env: TOXENV=py38-django22
    - python: 3.7
      env: TOXENV=py37-django30
    - python: 3.8
      env: TOXENV=py38-django30


before_cache:
  - rm -rf $HOME/.cache/pip/log


cache:
  directories:
    - $HOME/.cache/pip


install:
  - pip install tox


script:
  - tox
