# Generated by Django 3.2.6 on 2021-08-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_extensions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='data',
            field=models.JSONField(),
        ),
    ]
